behaviors:
  PushAgent2D:
    trainer_type: ppo
    max_steps: 3.0e6
    time_horizon: 32
    summary_freq: 1000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    hyperparameters:
      batch_size: 256
      buffer_size: 20480
      learning_rate: 5.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
    network_settings:
      normalize: true         
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

  AgentController2D:
    trainer_type: ppo
    max_steps: 1.0e6
    time_horizon: 64
    summary_freq: 1000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    hyperparameters:
      batch_size: 128              
      buffer_size: 10240           
      learning_rate: 5.0e-4        
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true             
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:                   
        gamma: 0.99
        strength: 0.01
        encoding_size: 128
        learning_rate: 1.0e-3

  EnemyShooter:
    trainer_type: ppo
    max_steps: 1.0e6
    time_horizon: 64
    summary_freq: 1000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    hyperparameters:
      batch_size: 256
      buffer_size: 40960
      learning_rate: 2.5e-4
      beta: 1.0e-2
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.01       
        encoding_size: 128
        learning_rate: 1.0e-3
