behaviors:
  EnemyAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 0.05
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    max_steps: 500000
    time_horizon: 128
    summary_freq: 10000
